Task 2: Approve teacher
B1ackMambaX/JavaTelegramBot pull request #10
Opened 2023-10-24 16:33 UTC by B1ackMambaX

Зацепленный бот: https://t.me/devhelper_kn_bot.
Issue about task: https://github.com/B1ackMambaX/JavaTelegramBot/issues/5

2023-10-28 15:21 UTC, vpyzhyanov requested changes
Есть замечания

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/bot/IBot.java
> +public interface IBot {
Отсутствует JavaDoc. Он для всех классов обязателен, а для интерфейсов вообще "Must Have", т.е. необходим. Все методы должны иметь JavaDoc

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/bot/IBot.java
> +    Object initKeyboard(User user);
Что за Object? Конкретно в этом методе вижу неразрывную связь с телеграммом

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/bot/IBot.java
> +    Object login(long chatId);
Что за Object? Для этого метода это точно не Object. Никогда не используйте Object без явной необходимости. Типизация - это сильная сторона Java не надо её в мусорку выкидывать

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
> +        User currentUser = userService.findUserByPlathformAndId(this.plathform, chatId);
этот код будет дублироваться в каждой чат-бот платформе. Не надо так. 

Весь этот метод login должен быть внутри `userService`, он работает только с ним. А тип платформы можно определить из интерфейса IBot, у него должен быть метод `getPlatform`. Хотя я бы его назвал ближе к сути, т.е. `getPlatformType`

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/dao/ProglangDao.java
> +        session.close();
сессии, как и потоки нужно корректно закрывать. Делается это либо в блоке finally, либо с помощью try-with-resources

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/dao/ProgquizDao.java
> +        session.close();
везде нужно сессию закрывать корректно

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/dao/ProgquizDao.java
> +        Transaction tx1 = session.beginTransaction();
работа с транзакциями тоже некорректна. Корректную работу можно вынести в отдельный метод, который выглядит примерно так:

```
public <T> T inTransaction(Callable<T> call) {
  final Session session = sessionFactory.getCurrentSession();
  final Transaction transaction = session.beginTransaction();
  try {
    final T result = call.call();
    transaction.commit();
    return result;
  } catch (final Exception e) {
    transaction.rollback();
    throw new RuntimeException(e);
  }
}
```

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +@Table(name = "public.user")
Имя схемы в имени таблицы? Зачем?

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +        this.setting_field_1 = "-1";
"магическая" константа. Лучше это вынести в константу с понятным названием

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/models/types/AnswerType.java
> + * Тип вопроса текстовый или вопрос с кодом
Здесь должно быть только "Тип вопроса", а описание каждого значения должно быть в JavaDoc самих значений

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Вас не смущает, что этот класс тупо делегирует всю работу `ProglangDao`, а сам ничего не делает? Меня смущает, поэтому он не нужен.

Ну и раз у пошла такая песня, то это не сервис, а репозиторий (Repository), т.е. слой, который отвечает за работу с данными. Хотя это термин, который навязал нам Spring и вы вовсе не обязаны его использовать. Но, тем не менее, это разграничивает сервис и слой работы с данными. А сервис - делает какую-то бизнес-логику, т.е. обрабатывает данные, которые он получил из репозитория.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/services/ProgquizService.java
> +public class ProgquizService {
аналогично, совершенно ненужный класс

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/services/UserService.java
> +public class UserService {
аналогично, совершенно ненужный класс. Хотя именно он должен инкапсулировать **логику** по работе с пользователем. Например операцию `login`. А не TelegramBot, как сейчас

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    private static SessionFactory sessionFactory;
![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/6093bf59-8dfe-4442-9cc1-439eb4a6d9f6)

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    public static SessionFactory getSessionFactory() {
static запрещён

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/logic/Logic.java
О шок, логику из проекта убрали! Куда? И главное зачем?

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +    public QuizHandler(Integer proglang_id) {
Переменная `proglang_id` всегда принимает значение 1. Значит она может быть удалена. **JavaDoc нигде нет, поэтому я даже предположить не могу зачем она была нужна.**

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/logic/stateManager/StateManager.java
> +            case IDLE:
Правда я ожидал, что автомат состояний будет не столь примитивным, а будет состоять из нескольких состояний и матрицы допустимых переходов. Хотя с другой стороны для текущего функционала - этого достаточно, но если понадобится усложнить, придётся переделывать.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/logic/stateManager/StateManager.java
> +                    quizHandler = new QuizHandler(1);
зачем его делать полем класса, если всё равно каждый раз создаётся новый инстанс?

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
> +            response = stateManager.chooseHandler(message, currentUser);
1. Описание этого метода говорит о том, что метод находится не там где должен. Он **использует** состояние, а не является им.
2. Название метода и его описание вводит нас в заблуждение, т.к. оно откровенно врёт. Оно говорит, что оно выбирает обработчик, а на самом деле оно выдаёт ответ. Похоже две функции слились воедино, а это плохо и непонятно.
3. Может всё-таки логику не стоило выкидывать? Пусть stateManager занимается тем, чем ему положено, т.е. управлением состояниями.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +    public String answerHandler(String message, User currentUser) {
Какую роль играет слово `Handler` в названии метода? Похоже никакую, только вводит в заблуждение, в переводе это звучит так "Обработчик ответа", что с реальностью не совпадает. Метод должен быть **глаголом**, а не существительным.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/main/Config.java
>      public static String getTelegramBotToken() {
static запрещён!

2023-10-28 15:21 UTC, vpyzhyanov commented on src/main/java/main/Config.java
> +    public static String getDatabaseHost() { return dotenv.get("DB_HOST"); }
static запрещён!

2023-10-28 15:21 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
> +    private StateManager logic;
теперь понятно куда логика потерялось. Она была смешана с состояниями. Не надо так. Логика использует состояния, но ими не является.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
> +     * Метод тестирующй логику бота
что такое "логика бота"? Это описание для класса, а не для метода. Метод должен тестировать **конкретные** вещи.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
>      private final String[] quizExpectedPhrases = {
Не надо выносить ожидаемые значение за пределы тестирующего метода, это не прозрачно и непонятно. Вы бы ещё в отдельный файл их вынесли)))

2023-10-28 15:21 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
> +        Assert.assertEquals("starting quiz", quizExpectedPhrases[0],
нет полноценного теста на квиз. Нужен тест, который будет делать правильные ответы и неправильные, который покажет, что квиз умеет оценивать ответы.

2023-10-28 15:21 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
> +        Assert.assertEquals("help command", startMessage, logic.chooseHandler("/help", testUser));
Сообщения для ассерта (первый аргумент) использованы не по назначению. В них нужно писать **человекочитаемое сообщение об ошибке**. Либо его вообще не добавлять.

2023-10-28 15:29 UTC, vpyzhyanov commented
![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/0cef8004-16ff-40f3-a6b1-f254d0639dad)

2023-10-28 16:25 UTC, begenFys commented on src/main/java/database/models/User.java
> +@Table(name = "public.user")
Потому что есть системная таблица user в postgresql, поэтому указывал схему

2023-10-28 16:29 UTC, begenFys commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Он понадобится дальше для работы  с выбором языков и статистики.
Также насчёт понятий слоёв: репозиторий и сервис, я бы обсудил это лично, так как нет большого опыта построения работы в Java и тут я не могу применить свои экспертные знания, мне казалось этого достаточно для работы с БД в боте

2023-10-28 16:29 UTC, begenFys commented on src/main/java/database/services/ProgquizService.java
> +public class ProgquizService {
Ответил выше

2023-10-28 16:29 UTC, begenFys commented on src/main/java/database/services/UserService.java
> +public class UserService {
Ответил выше

2023-10-28 16:31 UTC, begenFys commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    private static SessionFactory sessionFactory;
"Это не значит, что их вообще никогда нельзя использовать, это лишь значит ... и надо использовать их с умом" - не понимаю зачем мне делать инициализацию этого класса, который просто работает с сессиями

2023-10-28 16:32 UTC, begenFys commented on src/main/java/main/Config.java
>      public static String getTelegramBotToken() {
Тут я тоже не вижу смысла инициализировать класс, который просто работает с конфигом

2023-10-30 06:36 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
> +        Assert.assertEquals("help command", startMessage, logic.chooseHandler("/help", testUser));
Исправил [2778e64](https://github.com/B1ackMambaX/JavaTelegramBot/pull/10/commits/2778e64f90a9e17e4a558543ae6e51a6eff01e79)

2023-10-30 06:37 UTC, B1ackMambaX commented on src/main/java/logic/stateManager/StateManager.java
> +                    quizHandler = new QuizHandler(1);
Исправил [2778e64](https://github.com/B1ackMambaX/JavaTelegramBot/pull/10/commits/2778e64f90a9e17e4a558543ae6e51a6eff01e79)

2023-10-30 06:37 UTC, B1ackMambaX commented on src/main/java/logic/handlers/QuizHandler.java
> +    public QuizHandler(Integer proglang_id) {
Исправил [2778e64](https://github.com/B1ackMambaX/JavaTelegramBot/pull/10/commits/2778e64f90a9e17e4a558543ae6e51a6eff01e79)

2023-11-04 06:40 UTC, begenFys commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Пока решил оставить сервис для языков и квизов, так как говорил о реализации статистики и управления данными через админский доступ в боте. Думаю там будет чуть больше логики, если нет, то уберу сервисы и оставлю работу напрямую с DAO.

2023-11-06 14:38 UTC, B1ackMambaX commented on src/main/java/bot/IBot.java
> +    Object initKeyboard(User user);
Будет исправлено в третьей задаче вместе с реализацией отдельного класса для ответа на сообщение (как обсуждалось на паре)

2023-11-06 14:38 UTC, B1ackMambaX commented on src/main/java/database/dao/ProglangDao.java
> +        session.close();
fixed

2023-11-06 14:38 UTC, B1ackMambaX commented on src/main/java/database/dao/ProgquizDao.java
> +        session.close();
fixed

2023-11-06 14:39 UTC, B1ackMambaX commented on src/main/java/database/dao/ProgquizDao.java
> +        Transaction tx1 = session.beginTransaction();
fixed

2023-11-06 14:59 UTC, B1ackMambaX commented on src/main/java/bot/IBot.java
> +    Object login(long chatId);
fixed

2023-11-06 14:59 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
> +        User currentUser = userService.findUserByPlathformAndId(this.plathform, chatId);
Исправил, вынес в сервис

2023-11-06 15:00 UTC, B1ackMambaX commented on src/main/java/database/models/types/AnswerType.java
> + * Тип вопроса текстовый или вопрос с кодом
fixed

2023-11-06 15:00 UTC, B1ackMambaX commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    private static SessionFactory sessionFactory;
fixed

2023-11-06 15:00 UTC, B1ackMambaX commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    public static SessionFactory getSessionFactory() {
fixed

2023-11-06 15:01 UTC, B1ackMambaX commented on src/main/java/main/Config.java
>      public static String getTelegramBotToken() {
fixed

2023-11-06 15:01 UTC, B1ackMambaX commented on src/main/java/main/Config.java
> +    public static String getDatabaseHost() { return dotenv.get("DB_HOST"); }
fixed

2023-11-06 15:06 UTC, B1ackMambaX commented on src/main/java/bot/IBot.java
> +public interface IBot {
fixed

2023-11-06 15:10 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
> +        this.setting_field_1 = "-1";
fixed

2023-11-06 15:23 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
> +            response = stateManager.chooseHandler(message, currentUser);
Исправил, переписал джавадоки

2023-11-06 15:23 UTC, B1ackMambaX commented on src/main/java/logic/handlers/QuizHandler.java
> +    public String answerHandler(String message, User currentUser) {
Исправил, переписал джавадоки

2023-11-06 15:23 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
> +    private StateManager logic;
Исправил, переписал джавадоки

2023-11-06 17:21 UTC, B1ackMambaX commented
> ![image](https://user-images.githubusercontent.com/71599019/278822494-0cef8004-16ff-40f3-a6b1-f254d0639dad.png)

Исправил тесты

2023-11-06 17:21 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
> +        Assert.assertEquals("starting quiz", quizExpectedPhrases[0],
Исправил

2023-11-06 17:21 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
>      private final String[] quizExpectedPhrases = {
Исправил

2023-11-06 17:25 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
> +     * Метод тестирующй логику бота
Исправил

2023-11-06 17:25 UTC, B1ackMambaX commented
Исправили все замечания

2023-11-08 20:05 UTC, vpyzhyanov requested changes
Мне не понятно почему вы решили, что замечания можно не исправлять.

Нет тестов на handlersManager (логику бота)

Использовали static

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/services/UserService.java
> +    public User find(Integer user_id){
В этом классе куча методов, которые никем не используются. Если не используются, то должны быть удалены. Тут надо оставить только `login` и `update`

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/dao/ProglangDao.java
> +        Session session = sessionFactoryUtil.getSessionFactory().openSession();
Хорошо, что обработали сессию, но наплодили кучу дублирования кода. Почитайте что такое `Consumer` и `Function`. И можно будет делать так:
```
    public Proglang findByProglangId(Integer proglang_id) {
        return doInSession(session ->
                session.get(Proglang.class, proglang_id));
    }
```

А метод выглядит так:
```
    private <T> T doInSession(Function<Session, T> function) {
        Session session = sessionFactoryUtil.getSessionFactory().openSession();
        try {
            return function.apply(session);
        } catch (final Exception e) {
            System.out.println("Error: " + e);
            e.printStackTrace();
            return null;
        } finally {
            session.close();
        }
    }
```
Для транзакций можно сделать аналогичный.

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/dao/ProgquizDao.java
> +        Transaction tx1 = session.beginTransaction();
Похоже вы не дочитали замечание до конца и сделали только половину. Ну либо не поняли. А я ведь даже пример кода привёл.
Надо было вынести одинаковый код в общий метод.

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
> Он понадобится дальше для работы с выбором языков и статистики.

Вот не факт. Это всё вилами на воде писано, всё может поменяться. Поэтому ничего лишнего в коде быть не должно! Никаких лишних классов и никаких лишних методов.

Особое внимание обратите на то, что большинство методов в этом классе вообще нигде не вызываются, следовательно должны быть удалены.

> Думаю там будет чуть больше логики, если нет, то уберу сервисы и оставлю работу напрямую с DAO.

Ещё одна мудрость: нет ничего более постоянного, чем что-то временное

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/services/ProgquizService.java
> +public class ProgquizService {
Ни один метод класса не используется

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/services/UserService.java
> +public class UserService {
класс стал нужным, но содержит кучу совершенно ненужных методов

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    private static SessionFactory sessionFactory;
> - не понимаю зачем мне делать инициализацию этого класса, который просто работает с сессиями

Это проблема? В чём именно?

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    public static SessionFactory getSessionFactory() {
Зачем обманывать? Не исправлено
![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/a0b44bed-2133-4aad-ac3e-70fa087a3f28)

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/logic/Logic.java
Нет ответа на вопрос

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +    public QuizHandler(Integer proglang_id) {
Не исправлено. Только появился JavaDoc, который объяснил зачем она нужна. Тем не менее она всё равно не нужна, т.к. значение **всегда** одинаковое.

Возможно вы делая вторую задачу, уже делаете третью. Не надо так. За двумя зайцами погонитесь, ни одного не поймаете.

2023-11-08 20:05 UTC, vpyzhyanov commented on src/main/java/logic/handlersManager/handlersManager.java
> +public class handlersManager {
В соответствии с конвенцией именования классов, имя должно начинаться с большой буквы

2023-11-08 20:05 UTC, vpyzhyanov commented on src/test/java/logic/LogicTest.java
> +     * Метод тестирующй логику бота
Теперь нет тестов на `handlersManager`

2023-11-08 20:05 UTC, vpyzhyanov commented on src/test/java/logic/handlers/QuizHandlerTest.java
> +        questions.add(new Progquiz("Какой метод используется для фильтрации массива?", "filter"));
Зачем это всё инициализировать **каждый раз**? Тут возникает интересный эффект: к 10 тесту у вас будет уже 20 вопросов в списке)

Достаточно инициализации один раз на все тесты. Сделать это можно с помощью аннотации `@BeforeAll`

2023-11-09 07:49 UTC, begenFys commented on src/main/java/database/dao/ProgquizDao.java
> +        Transaction tx1 = session.beginTransaction();
Не совсем понял как вынести, поэтому пока оставил так. Думаю уточню на паре и в 3-4 задаче исправлю до конца

2023-11-11 13:49 UTC, B1ackMambaX commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Исправил, удалил

2023-11-11 13:50 UTC, B1ackMambaX commented on src/main/java/database/services/ProgquizService.java
> +public class ProgquizService {
Исправил

2023-11-11 13:50 UTC, B1ackMambaX commented on src/main/java/database/services/UserService.java
> +public class UserService {
Исправил

2023-11-11 13:50 UTC, B1ackMambaX commented on src/main/java/database/utils/HibernateSessionFactoryUtil.java
> +    public static SessionFactory getSessionFactory() {
Не обманул, а не заметил. Исправлено

2023-11-11 13:53 UTC, B1ackMambaX commented on src/main/java/logic/Logic.java
Мне кажется, мы обсуждали с Вами этот вопрос на паре. Логику никуда не убирали (иначе бот просто бы не работал), она все еще находится в пакете `logic`. Класс который ранее именовался `Logic` был переработан и переименован в `HandlersManager`, что точнее отражает функционал данного класса.

2023-11-11 13:54 UTC, B1ackMambaX commented on src/main/java/logic/handlers/QuizHandler.java
> +    public QuizHandler(Integer proglang_id) {
Да, действительно, это была затычка под будущий функционал. Исправил, убрал

2023-11-11 13:54 UTC, B1ackMambaX commented on src/test/java/logic/LogicTest.java
> +     * Метод тестирующй логику бота
Добавил тесты

2023-11-11 13:55 UTC, B1ackMambaX commented on src/main/java/logic/handlersManager/handlersManager.java
> +public class handlersManager {
Исправил

2023-11-11 13:56 UTC, B1ackMambaX commented on src/test/java/logic/handlers/QuizHandlerTest.java
> +        questions.add(new Progquiz("Какой метод используется для фильтрации массива?", "filter"));
К сожалению, аннотация @BeforeAll требует от тестирующего метода того, чтобы он был статичным, а static запрещен. Исправил вызовом конструктора

2023-11-11 13:57 UTC, B1ackMambaX commented on src/main/java/database/services/UserService.java
> +    public User find(Integer user_id){
Исправил

2023-11-11 16:12 UTC, B1ackMambaX commented on src/main/java/database/dao/ProglangDao.java
> +        Session session = sessionFactoryUtil.getSessionFactory().openSession();
Исправлено

2023-11-11 16:13 UTC, B1ackMambaX commented on src/main/java/database/dao/ProgquizDao.java
> +        Transaction tx1 = session.beginTransaction();
Исправлено

2023-11-13 11:15 UTC, vpyzhyanov requested changes
Всё хорошо, но есть пара мелочей. Как исправите, можете мёрджить. Задача принята.

2023-11-13 11:15 UTC, vpyzhyanov commented on src/main/java/database/dao/BaseDao.java
> +    public <T> T processSession(Function<Session, T> function) {
метод должен быть protected. Нельзя позволять никому извне открывать сессии безконтрольно

2023-11-13 11:15 UTC, vpyzhyanov commented on src/main/java/database/dao/BaseDao.java
> +    public <R> R processTransction(Function<Session, R> function) {
метод должен быть protected. Нельзя позволять никому извне открывать транзакции безконтрольно

2023-11-13 11:15 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Почему-то метод `findProgquizzesByProglangId` всё ещё существует

2023-11-13 11:44 UTC, B1ackMambaX commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id);
Этот метод существует т.к. он используется в следующей задаче

2023-11-13 18:03 UTC, B1ackMambaX commented on src/main/java/database/dao/BaseDao.java
> +    public <T> T processSession(Function<Session, T> function) {
fixed

2023-11-13 18:03 UTC, B1ackMambaX commented on src/main/java/database/dao/BaseDao.java
> +    public <R> R processTransction(Function<Session, R> function) {
fixed

2023-11-13 18:03 UTC, merged