Task 3: Approve from teacher
B1ackMambaX/JavaTelegramBot pull request #14
Opened 2023-11-07 22:01 UTC by begenFys

Issue(task description): https://github.com/B1ackMambaX/JavaTelegramBot/issues/11

2023-11-13 11:21 UTC, B1ackMambaX commented
P.S. Пока что правки из task-2 не были применены в task-3

2023-11-13 12:46 UTC, vpyzhyanov requested changes
Есть замечания. Не забудьте сделать rebase после того, как смёрджите 2 задачу.

2023-11-13 12:46 UTC, vpyzhyanov commented on README.md
> +2. [Task 2](https://github.com/B1ackMambaX/JavaTelegramBot/issues/5) - Переработка архитектуры и подключение базы данных.
Вижу тут только 2 задачу. Нет описания 3 задачи

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
>              e.printStackTrace();
Теперь есть лог. Это надо убрать.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
> +        Logger logger = Logger.getLogger(TelegramBot.class.getName());
Логгер надо сделать полем класса. Притом приватным.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
> +            e.printStackTrace();
Теперь есть лог. Это надо убрать.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/bot/TelegramBot.java
>              System.out.println(e.getMessage());
Теперь есть лог. Это надо убрать.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +    @Column (name = "setting_field_1")
Далеко не самые говорящие названия. Назовите колонку в соответствии со смыслом. Остальные колонки тоже

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +    private String setting_field_5;
Если вам нужна коллекция свойств, то создавайте коллекцию свойств (через JOIN). А то вдруг у вам понадобиться 6 настроек

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +    private String currentProglang;
вот тут смысл точно есть, насколько я вижу

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id).size();
1. этот сервис всё-ещё просто посредник между proglangDao.
2. Лучше количество записей определять запросом с использованием count. Так будет намного быстрее работать. Объекты не надо будет поднимать из базы.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(progalng_id).get(index);
здесь тоже надо специальным запросом, а то очень медленно будет работать

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        final List<Proglang> proglangs = proglangDao.findAll();
реализации следующих двух методов очень медленные тоже за счёт того, что поднимаются абсолютно все объекты. Если нужны имена достаточно запросить только имена.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +    public int checkExistenceOfProglang(String proglang_name) {
Описание метода не соответствует его сигнатуре. Вроде это "проверка на существование", но возвращает он не boolean а ID. Тогда пусть называется `getProglangIdByName`

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +        currentUser.setQurrentQuestion(Integer.toString(solvedCounter));
Зачем хранить числовые данные в строке? Да ещё и преобразовывать их туда-сюда. Нужно хранить в числовом виде. А то этим вы лишаете себя возможности агрегировать их, фильтровать и пр.

2023-11-13 12:46 UTC, vpyzhyanov commented on src/main/java/main/App.java
>              e.printStackTrace();
это надо удалить

2023-11-23 09:34 UTC, B1ackMambaX commented on README.md
> +2. [Task 2](https://github.com/B1ackMambaX/JavaTelegramBot/issues/5) - Переработка архитектуры и подключение базы данных.
fixed

2023-11-23 09:35 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
>              e.printStackTrace();
fixed

2023-11-23 09:36 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
> +        Logger logger = Logger.getLogger(TelegramBot.class.getName());
fixed

2023-11-23 09:37 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
> +            e.printStackTrace();
fixed

2023-11-23 09:37 UTC, B1ackMambaX commented on src/main/java/bot/TelegramBot.java
>              System.out.println(e.getMessage());
fixed

2023-11-23 09:38 UTC, B1ackMambaX commented on src/main/java/main/App.java
>              e.printStackTrace();
fixed

2023-11-23 09:41 UTC, B1ackMambaX commented on src/main/java/database/services/ProglangService.java
> +    public int checkExistenceOfProglang(String proglang_name) {
fixed

2023-11-28 09:44 UTC, begenFys commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id).size();
fixed

2023-11-28 09:44 UTC, begenFys commented on src/main/java/database/models/User.java
> +    private String setting_field_5;
fixed

2023-11-28 09:44 UTC, begenFys commented on src/main/java/database/models/User.java
> +    private String currentProglang;
fixed

2023-11-28 09:44 UTC, begenFys commented on src/main/java/database/models/User.java
> +    @Column (name = "setting_field_1")
fixed

2023-11-28 09:45 UTC, begenFys commented on src/main/java/logic/handlers/QuizHandler.java
> +        currentUser.setQurrentQuestion(Integer.toString(solvedCounter));
fixed

2023-11-28 17:57 UTC, B1ackMambaX commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(progalng_id).get(index);
Исправим в 4 задаче

2023-11-28 17:58 UTC, B1ackMambaX commented on src/main/java/database/services/ProglangService.java
> +        final List<Proglang> proglangs = proglangDao.findAll();
Исправим в 4 задаче

2023-12-04 20:04 UTC, vpyzhyanov commented
Такие вещи нельзя делать в открытом пулл реквесте. Вы создали мне проблемы при обновлении. А ещё вы этим могли затереть историю изменений

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/b1b61e84-7be0-42a7-85b6-16fc3790684c)

2023-12-04 20:10 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(proglang_id).size();
1 пункт не исправлен

2023-12-04 20:12 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        return proglangDao.findProgquizzesByProglangId(progalng_id).get(index);
> Исправим в 4 задаче

ок, проставлю баллы тоже в 4 задаче. Но вот незадача, вы не можете сдавать 4 задачу, пока не сдали третью)) В общем **такие ответы не принимаются!**

2023-12-04 20:13 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        final List<Proglang> proglangs = proglangDao.findAll();
аналогично. Ещё могу баллы в следующем году проставить, наверное так вам будет понятнее

2023-12-04 20:16 UTC, vpyzhyanov commented on src/main/java/database/services/ProglangService.java
> +        final List<Proglang> proglangs = proglangDao.findAll();
этот запрос тоже сильно не оптимален

2023-12-05 10:10 UTC, B1ackMambaX commented
Получили approve на паре

2023-12-05 10:10 UTC, merged