Task 4: Approve from teacher
B1ackMambaX/JavaTelegramBot pull request #23
Opened 2023-12-14 08:29 UTC by B1ackMambaX

Close issue [Task4](https://github.com/B1ackMambaX/JavaTelegramBot/issues/15)

2023-12-16 13:14 UTC, vpyzhyanov requested changes
Есть замечания

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/dao/StatisticsDao.java
> +        statistics.addAll(
лучше будет передать эту коллекцию сразу в конструктор. Тогда и конструктор будет сразу нужного размера, не придётся увеличивать размер коллекции, если она не влезет в размер по умолчанию.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/dao/StatisticsDao.java
> +        statistics.addAll(
аналогично

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Proglang.java
> +    private List<Statistics> statistics;
зачем тут это? При работе с языком программирования статистика не нужна. Статистика - отдельная сущность, пусть она и связана с языком и пользователем, но она очень слабо к ним относится. Притом относится сразу к обоим, а это должно было вас насторожить. В общем, незачем её тащить в entity. Работайте со статистикой через сервис статистики и DAO.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +public class Statistics {
Неуместно использовать множественное число в именах классов и пакетов. Даже само слово "Статистика" не имеет множественного числа, а тут вы множетственное делаете. Множественное число уместно использовать только для коллекций.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +package database.models;
Неуместно использовать множественное число в именах классов и пакетов. И ежу понятно что в каталоге может быть несколько объектов.

Остальные пакеты тоже прошу переименовать.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    private int id;
Скажите, пожалуйста, какое максимальное значение у int? Ничего вас не смущает?

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    private Integer score;
странно, что это объектный тип. Можно же присваивать по умолчанию 0.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Statistics() {}
модификатор доступа должен быть private. И нечего в тестах использовать этот конструктор! Он не для тестов нужен, а для хибернейта

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
откуда вдруг взялся объектный тип? И зачем вы лишний раз нагружаете процессор и память?

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +                            public String toString() {
похоже вы забываете пользоваться форматированием, очень зря. Его легко настроить, чтобы оно делалось при каждом коммите

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +        return "Score:" + user.getId() + " " + proglang.getName() + " " + score;
Не очень удачно получилось у вас написать удобную отладочную строку. Воспользуйтесь генератором кода в IDEA, она сделает это намного лучше и удобнее.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
>      private Quizstate quizstate;
это поле не используется и должно быть удалено

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +    private List<Statistics> statistics;
аналогичное замечание про то, что этого поля тут быть не должно. Ну и вы его и так не используете. Удалить

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +        this.plathform_username = plathform_username;
Для переменных, полей и методов принято использовать `camelCase`, прошу переименовать все поля, переменные и методы в соответствующий вид

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
>       * @param state состояние пользователя
забыли обновить описание?

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/database/models/User.java
> +        this.plathform_username = plathform_username;
не принципиально, но добавлять эту строчку следовало в конец метода

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +    private void saveStatistics(User user, Integer count, Proglang proglang) {
Добро пожаловать на тёмную сторону ООП. Ваш класс перегружен функционалом. Почему вы решили, что обработчик квиза должен заниматься управлением статистикой?! Весь этот метод должен быть в `StatisticService`, как и всё что связано со статистикой. А тут лишь надо вызывать этот сервис.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +package logic.handlers;
опять множественное число

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +        keyboardMessagesIdle.add("/leaderboard");
дублирование кода. Тут надо было вызывать конструктор через `this(...)`

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +            Long sumTotal = 0L;
неуместное использование объектных типов. Их польза начинается только при использовании в качестве дженериков и для возможности установить null. У вас нет ни того, ни другого.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +                responseMessage += proglang.getName() + ": " + userQuestions + "/" + totalQuestions + "\n";
Вас же IDEA предупреждает, что вы используете конкатенацию в цикле. В этом случае надо использовать StringBuilder

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +                    return o2.getScore() - o1.getScore();
Никогда не используйте в качестве сравнения операцию вычитания. Это не очевидно. Лучше так:

```java
rawStats.sort((o1, o2) -> Integer.compare(o1.getScore(), o2.getScore()));
```

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +                rawStats = rawStats.subList(0, 10);
Скажите "давай до свидания" производительности вашего приложения. Вы правда хотите достать из базы миллион объектов, чтобы взять только 10? Наверное нет. Если вам нужно только 10 объектов используйте ключевое слово `LIMIT` в вашем запросе к БД. То есть ограничить список нужно на уровне БД.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/main/java/logic/handlersManager/HandlersManager.java
> +                    userService.update(currentUser);
на лицо ещё одна тёмная грань ООП: размазанная ответственность. Вы же вроде поручили управлять командами соответствующий Handler, но изменить состояние ему не доверяете. А ведь зря, именно команда меняет состояние. А может и не менять, например в случае ошибки, но это уже её ответственность, а не HandlersManager. Задача HandlersManager - перенаправить запрос к нужному обработчику и больше ничего.

P.S. HandlersManager - тоже неуместное использование множественного числа, и ежу понятно, что он управляет всеми обработчиками.

2023-12-16 13:14 UTC, vpyzhyanov commented on src/test/java/logic/handlers/HandlersManagerTest.java
> +        Assertions.assertEquals(testUser.getState(), State.LEADERBOARD, "Тест на команду /leaderboard");
1. А где тест на состояние `LEADERBOARD`, т.е. метод `statisticHandler.getLeaderboard`?
2. А где тест на команду `/mystats`?

2023-12-16 13:26 UTC, B1ackMambaX commented on src/test/java/logic/handlers/HandlersManagerTest.java
> +        Assertions.assertEquals(testUser.getState(), State.LEADERBOARD, "Тест на команду /leaderboard");
Они находятся в `StatisticHandlerTest`

2023-12-16 13:33 UTC, begenFys commented on src/main/java/database/models/Statistics.java
> +public class Statistics {
![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/45749794/a762a9e0-e065-4d50-8d61-4af8b45d88ae)

2023-12-16 13:53 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +package database.models;
На мой взгляд, нейминг пакетов - сугубо субъективная вещь. Мне, например, когда я смотрю чей-то гитхаб репозиторий, непонятно что в папке `model` может лежать несколько сущностей. Нейминг же во множественном числе мне кажется куда более очевидным, к тому же такой нейминг зачастую
 используется создателями библиотек.
<img width="888" alt="Снимок экрана 2023-12-16 в 18 44 04 1" src="https://github.com/B1ackMambaX/JavaTelegramBot/assets/114356998/982f797f-8023-445d-a9fb-a798f299424d">
<img width="713" alt="Снимок экрана 2023-12-16 в 18 52 20" src="https://github.com/B1ackMambaX/JavaTelegramBot/assets/114356998/f6953432-0ee2-4065-9c5e-03a3ded11338">

2023-12-16 13:59 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +package logic.handlers;
Ответил выше

2023-12-16 14:12 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +                rawStats = rawStats.subList(0, 10);
Исправил

2023-12-16 14:13 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +                    return o2.getScore() - o1.getScore();
Сортировка теперь происходит внутри statisticsDao с помощью запроса к БД

2023-12-16 14:22 UTC, B1ackMambaX commented on src/main/java/logic/handlers/QuizHandler.java
> +    private void saveStatistics(User user, Integer count, Proglang proglang) {
Исправил

2023-12-16 14:25 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
>      private Quizstate quizstate;
Исправил

2023-12-16 14:25 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
> +    private List<Statistics> statistics;
Исправил

2023-12-16 14:25 UTC, B1ackMambaX commented on src/main/java/database/models/Proglang.java
> +    private List<Statistics> statistics;
Исправил

2023-12-16 14:33 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +                            public String toString() {
Исправил

2023-12-16 14:33 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +        return "Score:" + user.getId() + " " + proglang.getName() + " " + score;
Исправил

2023-12-16 14:57 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    private int id;
Исправил

2023-12-16 14:57 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    private Integer score;
Исправил

2023-12-16 14:57 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
Исправил

2023-12-16 14:59 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
>       * @param state состояние пользователя
Да, исправил

2023-12-16 14:59 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
> +        this.plathform_username = plathform_username;
Исправил

2023-12-16 15:00 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +            Long sumTotal = 0L;
Исправил

2023-12-16 15:04 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +        keyboardMessagesIdle.add("/leaderboard");
Исправил

2023-12-16 15:05 UTC, B1ackMambaX commented on src/main/java/logic/handlers/StatisticHandler.java
> +                responseMessage += proglang.getName() + ": " + userQuestions + "/" + totalQuestions + "\n";
Исправил

2023-12-16 15:21 UTC, B1ackMambaX commented on src/main/java/database/models/User.java
> +        this.plathform_username = plathform_username;
Исправил, @begenFys спасибо за 15 минут исправления твоего snake кейса <3

2023-12-16 15:23 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    public Statistics() {}
Исправил

2023-12-16 16:14 UTC, B1ackMambaX commented on src/main/java/logic/handlersManager/HandlersManager.java
> +                    userService.update(currentUser);
Исправил

2023-12-16 16:20 UTC, B1ackMambaX commented on src/main/java/database/dao/StatisticsDao.java
> +        statistics.addAll(
Исправил

2023-12-16 16:20 UTC, B1ackMambaX commented on src/main/java/database/dao/StatisticsDao.java
> +        statistics.addAll(
Исправил

2023-12-16 16:20 UTC, B1ackMambaX commented on src/main/java/logic/handlersManager/HandlersManager.java
> +                    userService.update(currentUser);
По поводу множественного числа ответил выше

2023-12-16 16:44 UTC, vpyzhyanov commented on src/main/java/database/dao/StatisticsDao.java
> +                .setMaxResults(10)
это нужно обязательно отразить в JavaDoc, чтобы это не было ни для кого неожиданностью

2023-12-16 16:44 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +public class Statistics {
Не исправлено

2023-12-16 16:44 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +package database.models;
не исправлено

2023-12-16 16:45 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Statistics() {}
Лжёте

2023-12-16 16:47 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
Интересно, а вы поняли почему нагружается процессор и память?

2023-12-16 16:50 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
Потому что это не примитив а экземляр класса(объект) Integer

2023-12-16 16:51 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +public class Statistics {
А вот это уже аргумент, ок

2023-12-16 16:51 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    public Statistics() {}
Прямо сейчас исправил видимо когда ctrl + z нажимал отменил случайно

2023-12-16 16:54 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +package database.models;
>  непонятно что в папке model может лежать несколько сущностей

Правда? Вы не знаете, что каталоге может лежать более одного файла? Странно))))) Ну ладно, как хотите, всё-таки момент не принципиальный и на ООП не влияет.

2023-12-16 16:55 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
да, но при чём тут память и процессор?

2023-12-16 16:58 UTC, B1ackMambaX commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
Будет вызываться (хоть здесь и нет явного вызова) конструктор, что нагружает процессор, а экземпляр класса хранит все его методы, что нагружает ОП.

2023-12-16 16:59 UTC, vpyzhyanov commented on src/main/java/logic/handlers/QuizHandler.java
> +            keyboardMessages = Arrays.asList("/help", "/quiz", "/mystats", "/leaderboard");
лучше `List.of(...)`. Принципиальной разницы нет, но так более модно и молодёжно. А может даже более производительно.

2023-12-16 16:59 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +        keyboardMessagesIdle.add("/leaderboard");
Похоже вы меня не поняли, я просил избавиться от дублирования кода.

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/cd6282b6-3943-400e-ae23-7601d5156c7c)

2023-12-16 17:01 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +        keyboardMessagesIdle.add("/leaderboard");
Делается это так:

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/8bce2f19-b89a-4905-a8bc-ca1025cc8264)

2023-12-16 17:03 UTC, vpyzhyanov commented on src/main/java/logic/handlers/StatisticHandler.java
> +                    return o2.getScore() - o1.getScore();
а это ещё лучше

2023-12-16 17:05 UTC, vpyzhyanov commented on src/main/java/logic/handlersManager/HandlersManager.java
> +                    userService.update(currentUser);
ну вот, и код стал заметно более красивым, кратким и понятным

2023-12-16 17:15 UTC, vpyzhyanov commented on src/test/java/logic/handlers/HandlersManagerTest.java
> +        Assertions.assertEquals(testUser.getState(), State.LEADERBOARD, "Тест на команду /leaderboard");
Тем не мене обработкой команд изначально занимается `HandlersManager` необходимо так же проверять и его, что он правильно передаёт управление нужному обработчику.

Впрочем я попытался сломать ваш код, но тесты всё-таки упали. Тогда всё хорошо.

2023-12-16 17:17 UTC, vpyzhyanov commented
Поспешили коммитить, я смотрю, не проверили код, не запустили тесты

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/18dd1185-3686-4de6-a9ef-f9c531fdc71a)

2023-12-16 17:17 UTC, B1ackMambaX commented on src/test/java/logic/handlers/HandlersManagerTest.java
> +        Assertions.assertEquals(testUser.getState(), State.LEADERBOARD, "Тест на команду /leaderboard");
В тесте` HandlersManagerTest` и проверяется какому из обработчиков он отдаст сообщение в зависимости от состояния и собственно самого сообщения

2023-12-16 17:19 UTC, vpyzhyanov commented on src/main/java/database/models/Statistics.java
> +    public Integer getId() {
ну да, всё верно. Будет производиться boxing каждый раз, т.к. поле примитив, а возвращаемое значение - объект.

2023-12-16 17:21 UTC, B1ackMambaX commented
> Поспешили коммитить, я смотрю, не проверили код, не запустили тесты
> 
> ![image](https://private-user-images.githubusercontent.com/71599019/291006623-18dd1185-3686-4de6-a9ef-f9c531fdc71a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDc1MDQsIm5iZiI6MTcwMjc0NzIwNCwicGF0aCI6Ii83MTU5OTAxOS8yOTEwMDY2MjMtMThkZDExODUtMzY4Ni00ZGU2LWE5ZWYtZjljNTMxZmRjNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE3MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YmY3ZDY0ZGI3ZTg1ZTM3MWYzY2E4NThhMjk3Mjg4OTVmM2M0MDYwOWU3OTViNjdiMmQwZWFhMTgwMWZlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fg1SW0hDzPxgZEbOdblaJ2X6Aw97Dd0K296w0Btkcfs)

Согласен, пропустил, нам теперь гарантируется что должен приходить уже отсортированный список

2023-12-19 09:52 UTC, B1ackMambaX commented
Получили апрув на паре

2023-12-19 09:52 UTC, merged