Task 1. Approve Teacher
B1ackMambaX/JavaTelegramBot pull request #4
Opened 2023-10-09 18:18 UTC by begenFys

Issue about task: https://github.com/B1ackMambaX/JavaTelegramBot/issues/2

2023-10-12 19:24 UTC, vpyzhyanov requested changes
tofix

2023-10-12 19:24 UTC, vpyzhyanov commented on .idea/.gitignore
Мусор в репозитории

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/5fb9d5aa-3f9d-44f4-a922-0886fc3ca54f)

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/46e19735-92c1-484b-8aff-566f149fa90d)

2023-10-12 19:24 UTC, vpyzhyanov commented on .gitignore
Не надо добавлять файлы по отдельности, укажите всю папку целиком

![image](https://github.com/B1ackMambaX/JavaTelegramBot/assets/71599019/80fda08e-40c0-4d41-9ca2-903b1b062571)

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/bot/Bot.java
>  public class Bot extends TelegramLongPollingBot {
Имя класса не совпадает с его описанием и смыслом. Это `TelegrammBot`

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/bot/Bot.java
>      final private String BOT_TOKEN = main.Config.getTelegramBotToken();
Лучше сделать import

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> + * Класс, который реализует вопрос в квизе
Не надо лишних вводных конструкций. Просто "Вопрос в квизе"

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +     * @param type - тип ответа(text or code)
Описание намекает на то, что тип `type` должен быть enum

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +public class Question {
можно использовать ключевое слово record и не писать геттеры

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +     *
Где описание?

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +                "Вы ответили неправильно! Правильный ответ:" + this.questionAnswer + '\n';
Тернарный оператор более читаем при таком форматировании:

```
    public String checkCorrectness(String answer) {
        return answer.equals(this.questionAnswer)
                ? "Вы ответили правильно!\n"
                : "Вы ответили неправильно! Правильный ответ:" + this.questionAnswer + '\n';
    }
```

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +    public String checkCorrectness(String answer) {
Проверять правильность - это ответственность явно не вопроса. Это просто POJO класс, в нём не должно быть логики.

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Storage.java
> +    private final ArrayList<Question> questions;
Используйте интерфейс, а не класс `List<Question>`

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Storage.java
> +        questions.add(new Question(0, 0, "Какой метод используется для фильтрации массива?", "filter", "text"));
В будущих задачах это надо будет вынести в какой-то источник данных. В файл или БД

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/data/Storage.java
> +    public ArrayList<Question> getAllQuestions() {
интерфейс

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/logic/Logic.java
> +    private String quizHandler(String message) {
Это достойно отдельного класса

2023-10-12 19:24 UTC, vpyzhyanov commented on src/main/java/main/App.java
> +public class  App
Где JavaDoc?

2023-10-12 19:24 UTC, vpyzhyanov commented on src/test/java/logic/MessageParserUnitsTest.java
> +    public void testParser() {
У класса и у **всех методов** должен быть JavaDoc

2023-10-12 19:24 UTC, vpyzhyanov commented on src/test/java/logic/MessageParserUnitsTest.java
> +            "Вы ответили правильно!\nКакой метод используется для поиска индекса элемента в массиве?",
Зачем весь тест проходить? Хватит двух вопросов с правильным и неправильным ответами.

2023-10-12 19:30 UTC, begenFys commented on src/main/java/bot/Bot.java
>  public class Bot extends TelegramLongPollingBot {
Принял, поправим

2023-10-12 19:31 UTC, begenFys commented on .gitignore
Это стандартный .gitignore который лежит на просторах сия гитхаба, его и брали. Также у Артёма возникали проблема с билдом проекта из-да отсутствия папки .idea

2023-10-12 19:32 UTC, begenFys commented on src/main/java/data/Question.java
> +     * @param type - тип ответа(text or code)
Должен и будет, когда будет полноценная ORM и БД, спасибо за замечание

2023-10-12 19:32 UTC, begenFys commented on src/main/java/data/Question.java
> +public class Question {
О таком не знали, изучим, спасибо

2023-10-12 19:33 UTC, begenFys commented on src/main/java/data/Question.java
> +                "Вы ответили неправильно! Правильный ответ:" + this.questionAnswer + '\n';
Приняли, спасибо

2023-10-12 19:34 UTC, begenFys commented on src/main/java/data/Storage.java
> +    private final ArrayList<Question> questions;
Поправим этот вопрос во второй задаче, спасибо

2023-10-12 19:34 UTC, begenFys commented on src/main/java/data/Storage.java
> +        questions.add(new Question(0, 0, "Какой метод используется для фильтрации массива?", "filter", "text"));
Так и есть, спасибо

2023-10-12 19:35 UTC, begenFys commented on src/main/java/main/App.java
> +public class  App
Пропал... Поправим, спасибо

2023-10-12 19:36 UTC, begenFys commented on src/main/java/logic/Logic.java
> +    private String quizHandler(String message) {
Может стоит тогда Handler как сущность вынести в интерфейс, и из него делать разные классы? (Хотя не знаю насколько это целесообразно, учитывая, что у многих хендлеров логика будет отличаться кардинально)

2023-10-12 19:40 UTC, vpyzhyanov commented on .gitignore
В этом плане этот стандартный файл заполнен неудачно.

>  Также у Артёма возникали проблема с билдом проекта из-да отсутствия папки .idea

Вообще-то папка .idea создаётся, когда вы выкачиваете проект. У всех настройки проекта разные, коммитить и портить проект другим разрботчикам не нужно.

2023-10-12 19:42 UTC, vpyzhyanov commented on src/main/java/logic/Logic.java
> +    private String quizHandler(String message) {
Вы сами ответили на свой вопрос) Раз они кардинально разные, то ничего общего у них быть не должно. Просто у каждого будет своя ответственность и свои методы.

2023-10-13 07:52 UTC, begenFys commented on .idea/.gitignore
FIXED

2023-10-13 07:52 UTC, begenFys commented on .gitignore
FIXED

2023-10-13 08:07 UTC, begenFys commented on src/main/java/bot/Bot.java
>  public class Bot extends TelegramLongPollingBot {
FIXED

2023-10-13 08:07 UTC, begenFys commented on src/main/java/bot/Bot.java
>      final private String BOT_TOKEN = main.Config.getTelegramBotToken();
Тут не понял

2023-10-13 08:08 UTC, begenFys commented on src/main/java/data/Question.java
> + * Класс, который реализует вопрос в квизе
FIXED

2023-10-13 08:10 UTC, begenFys commented on src/main/java/data/Question.java
> +     *
FIXED

2023-10-13 08:10 UTC, begenFys commented on src/main/java/data/Question.java
> +                "Вы ответили неправильно! Правильный ответ:" + this.questionAnswer + '\n';
FIXED

2023-10-13 08:11 UTC, begenFys commented on src/main/java/main/App.java
> +public class  App
FIXED

2023-10-13 08:12 UTC, begenFys commented on src/test/java/logic/MessageParserUnitsTest.java
> +    public void testParser() {
FIXED

2023-10-13 14:44 UTC, B1ackMambaX commented on src/main/java/data/Question.java
> +public class Question {
Исправил в коммите [08с0532](https://github.com/B1ackMambaX/JavaTelegramBot/pull/4/commits/08c05329f54b11a50ba24e1aefa42535f18572ed)

2023-10-13 14:45 UTC, B1ackMambaX commented on src/main/java/data/Question.java
> +    public String checkCorrectness(String answer) {
Исправил в коммите [7c09d69](https://github.com/B1ackMambaX/JavaTelegramBot/pull/4/commits/7c09d69516b7ae3bcd76fb37f5490f2bd1bb1e8d)

2023-10-13 14:46 UTC, B1ackMambaX commented on src/main/java/data/Storage.java
> +    private final ArrayList<Question> questions;
Исправил в коммите [1dab550](https://github.com/B1ackMambaX/JavaTelegramBot/pull/4/commits/1dab55054a86044dd480947b0243401114f1cfc2)

2023-10-13 14:47 UTC, B1ackMambaX commented on src/main/java/data/Storage.java
> +    public ArrayList<Question> getAllQuestions() {
Исправил в коммите [1dab550](https://github.com/B1ackMambaX/JavaTelegramBot/pull/4/commits/1dab55054a86044dd480947b0243401114f1cfc2)

2023-10-13 14:47 UTC, B1ackMambaX commented on src/main/java/logic/Logic.java
> +    private String quizHandler(String message) {
Исправил в коммите [7c09d69](https://github.com/B1ackMambaX/JavaTelegramBot/pull/4/commits/7c09d69516b7ae3bcd76fb37f5490f2bd1bb1e8d)

2023-10-13 14:49 UTC, B1ackMambaX commented
Исправил все замечания

2023-10-14 11:47 UTC, vpyzhyanov commented
Прошу не отмечать замечания как "решённые" самовольно. Только тот, **кто писал замечание** может оценить решено оно или нет.

2023-10-14 11:52 UTC, vpyzhyanov commented on src/main/java/bot/Bot.java
>      final private String BOT_TOKEN = main.Config.getTelegramBotToken();
Класс `Config` используется с указанием пакета. Пакет нужно вынести в импорт. Да ещё слово `main` сбивает с толку, можно подумать, что это поле класса (изначально я хотел написать замечание на это, но потом увидел, что пакет)

2023-10-14 12:15 UTC, vpyzhyanov requested changes
Есть небольшие замечания. Как исправите, можете сразу мёрджить. Задача принята.

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +     * @param id             - id вопроса
Не рекомендую форматировать комментарии, это неудобно. Если одно поле 2 символа, а другое 30, то это будет выглядеть так себе

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/data/Question.java
> +     * @param type - тип ответа(text or code)
Не исправлено! Это замечание никак не относится ни к ORM, ни к БД. Поэтому это не может быть аргументом не делать это сейчас.

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/logic/Logic.java
> +     * Метод позволяющий изменять значение isQuiz внутри других классов пакета logic
нарушение инкапсуляции, пожалуйста, исправьте это, когда будете делать состояния.

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/logic/QuizHandler.java
> +public class QuizHandler {
Нет описания

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/logic/QuizHandler.java
> +        this.logic = logic;
Лишняя циклическая связь. Пусть лучше `Logic `самостоятельно спросит у `QuizHandler ` закончился квиз или нет. Тогда этой связи не будет.

2023-10-14 12:15 UTC, vpyzhyanov commented on src/main/java/logic/QuizHandler.java
> +            throw new RuntimeException("Error in quiz logic");
А вы обрабатываете эти исключения? Или вы предпочитате положить бота?

2023-10-14 12:15 UTC, vpyzhyanov commented on src/test/java/logic/MessageParserUnitsTest.java
> +     * Запуск теста
описание теста и его название не соответствуют друг другу. Что вообще такое `Запуск теста`? Запуск теста не может находиться в тесте.

В описании теста нужно писать что вы тестируете.

2023-10-14 12:15 UTC, vpyzhyanov commented on src/test/java/logic/MessageParserUnitsTest.java
> +            "Вы ответили правильно!\nКакой метод используется для поиска индекса элемента в массиве?",
Примечательный пример с попыткой обмануть ревьюера. Замечание не исправили, а пометили как решённое. Ох некрасиво как.

2023-10-14 12:51 UTC, B1ackMambaX commented on src/test/java/logic/MessageParserUnitsTest.java
> +     * Запуск теста
Исправил

2023-10-14 12:52 UTC, B1ackMambaX commented on src/main/java/logic/QuizHandler.java
> +            throw new RuntimeException("Error in quiz logic");
Исправил

2023-10-14 12:52 UTC, B1ackMambaX commented on src/main/java/logic/QuizHandler.java
> +        this.logic = logic;
Будет исправлено вместе с реализацией состояний

2023-10-14 12:52 UTC, B1ackMambaX commented on src/main/java/logic/QuizHandler.java
> +public class QuizHandler {
Исправил

2023-10-14 12:52 UTC, B1ackMambaX commented on src/main/java/data/Question.java
> +     * @param id             - id вопроса
Исправил

2023-10-14 12:53 UTC, B1ackMambaX commented on src/test/java/logic/MessageParserUnitsTest.java
> +            "Вы ответили правильно!\nКакой метод используется для поиска индекса элемента в массиве?",
Теперь точно исправил

2023-10-14 12:53 UTC, B1ackMambaX commented on src/main/java/bot/Bot.java
>      final private String BOT_TOKEN = main.Config.getTelegramBotToken();
Исправил

2023-10-14 12:53 UTC, B1ackMambaX commented on src/main/java/data/Question.java
> +     * @param type - тип ответа(text or code)
Исправил

2023-10-14 12:54 UTC, merged